#!/usr/bin/env python3
"""
Emits njtransit.pnml and lang/english.lng from the fleet table.

The GRF carries both stat sets. Realistic values are written as ordinary
properties; the game-balanced ones follow inside an `if (stats == 1)` block,
which OpenTTD resolves at load time with an Action 7 skip, so the NewGRF
parameter picks between them without needing two files.
"""

import os

from fleet import VEHICLES, BY_ID

HERE = os.path.dirname(os.path.abspath(__file__))
OVERRIDE_KEYS = ["speed", "power", "weight", "cap", "cost", "run",
                 "model_life", "life", "decay"]

HEADER = '''/*
 * NJ TRANSIT + PATH Trainset for OpenTTD
 * --------------------------------------
 * Generated by gen_nml.py from fleet.py - edit those, not this file.
 *
 * NewGRF parameter 0 ("stats") picks the stat set:
 *   0 = realistic  (published prototype figures)
 *   1 = balanced   (tuned to sit alongside OpenTTD's own vehicles)
 */

grf {
    grfid:                  "NJT\\01";
    name:                   string(STR_GRF_NAME);
    desc:                   string(STR_GRF_DESC);
    version:                2;
    min_compatible_version: 1;
    param {
        stats {
            type:      int;
            name:      string(STR_PARAM_STATS);
            desc:      string(STR_PARAM_STATS_DESC);
            min_value: 0;
            max_value: 1;
            def_value: 0;
            names: {
                0: string(STR_PARAM_REALISTIC);
                1: string(STR_PARAM_BALANCED);
            };
        }
    }
}

railtypetable { RAIL, ELRL }
cargotable    { PASS, MAIL }

/* Every sheet is 8 cells of 52x40 px, one per direction (N, NE, E, SE, S, SW,
 * W, NW), drawn around a common reference point so consists line up. */
template tmpl_8views(row) {
    [   0, row, 52, 40, -26, -26]
    [  52, row, 52, 40, -26, -26]
    [ 104, row, 52, 40, -26, -26]
    [ 156, row, 52, 40, -26, -26]
    [ 208, row, 52, 40, -26, -26]
    [ 260, row, 52, 40, -26, -26]
    [ 312, row, 52, 40, -26, -26]
    [ 364, row, 52, 40, -26, -26]
}
'''


def prop_line(key, value, pad=32):
    return "        {}{}\n".format((key + ":").ljust(pad), str(value) + ";")


def item_block(v, mode="real"):
    s = v[mode]
    out = "item(FEAT_TRAINS, {}, {}) {{\n    property {{\n".format(v["nml"], v["id"])
    p = ""
    p += prop_line("name", "string(STR_NAME_{})".format(v["nml"].upper()))
    p += prop_line("climates_available",
                   "NO_CLIMATE" if v.get("hidden") else "ALL_CLIMATES")
    p += prop_line("introduction_date", "date({}, {}, {})".format(*v["intro"]))
    p += prop_line("model_life", s["model_life"])
    p += prop_line("vehicle_life", s["life"])
    p += prop_line("reliability_decay", s["decay"])
    p += prop_line("cost_factor", s["cost"])
    p += prop_line("running_cost_factor", s["run"])
    p += prop_line("running_cost_base", v["run_base"])
    p += prop_line("speed", "{} mph".format(s["speed"]))
    p += prop_line("power", "{} hp".format(s["power"]))
    p += prop_line("weight", "{} ton".format(s["weight"]))
    p += prop_line("tractive_effort_coefficient", v["te"])
    p += prop_line("air_drag_coefficient", v["drag"])
    p += prop_line("length", v["length"])
    p += prop_line("track_type", v["track"])
    if v.get("engine_class"):
        p += prop_line("engine_class", v["engine_class"])
    if v.get("effect"):
        p += prop_line("visual_effect_and_powered",
                       "visual_effect_and_powered({}, 0, DISABLE_WAGON_POWER)"
                       .format(v["effect"]))
    if v.get("flags"):
        p += prop_line("misc_flags", "bitmask({})".format(", ".join(v["flags"])))
    if s["cap"]:
        p += prop_line("refittable_cargo_classes", "bitmask(CC_PASSENGERS)")
        p += prop_line("cargo_capacity", s["cap"])
        p += prop_line("loading_speed", v.get("loading", 20))
    else:
        p += prop_line("cargo_capacity", 0)
    p += prop_line("sprite_id", "SPRITE_ID_NEW_TRAIN")
    out += p + "    }\n    graphics {\n"
    out += "        default:                   set_{}\n".format(v["sprite"]).replace(
        "set_{}\n".format(v["sprite"]), "set_{};\n".format(v["sprite"]))
    if v.get("artic"):
        out += "        articulated_part:          sw_{}_artic;\n".format(v["nml"])
    if v.get("dual"):
        out += "        power:                     sw_{}_power_real;\n".format(v["nml"])
        out += "        visual_effect_and_powered: sw_{}_effect;\n".format(v["nml"])
    if v.get("purchase"):
        out += "        additional_text:           string(STR_PURCHASE_{});\n".format(
            v["nml"].upper())
    out += "    }\n}\n"
    return out


def override_block(v):
    """Only the properties whose balanced value differs from the realistic one."""
    real, bal = v["real"], v["bal"]
    diffs = [k for k in OVERRIDE_KEYS if real[k] != bal[k]]
    if not diffs and not v.get("dual"):
        return ""
    out = "    item(FEAT_TRAINS, {}) {{\n        property {{\n".format(v["nml"])
    fmt = {
        "speed": lambda x: ("speed", "{} mph".format(x)),
        "power": lambda x: ("power", "{} hp".format(x)),
        "weight": lambda x: ("weight", "{} ton".format(x)),
        "cap": lambda x: ("cargo_capacity", x),
        "cost": lambda x: ("cost_factor", x),
        "run": lambda x: ("running_cost_factor", x),
        "model_life": lambda x: ("model_life", x),
        "life": lambda x: ("vehicle_life", x),
        "decay": lambda x: ("reliability_decay", x),
    }
    for k in diffs:
        key, val = fmt[k](bal[k])
        out += "    " + prop_line(key, val, pad=28)
    out += "        }\n"
    if v.get("dual"):
        out += "        graphics {\n"
        out += "            default:                   set_{};\n".format(v["sprite"])
        out += "            power:                     sw_{}_power_bal;\n".format(v["nml"])
        out += "            visual_effect_and_powered: sw_{}_effect;\n".format(v["nml"])
        out += "            additional_text:           string(STR_PURCHASE_{});\n".format(
            v["nml"].upper())
        out += "        }\n"
    out += "    }\n"
    return out


def main():
    for i, v in enumerate(VEHICLES):
        v["id"] = i

    out = HEADER + "\n"
    for v in VEHICLES:
        out += 'spriteset(set_{0}, "sprites/{0}.png") {{ tmpl_8views(0) }}\n'.format(
            v["sprite"])

    # dual-power and articulation switches
    out += "\n/* ------------------------------------------------- callbacks -- */\n"
    for v in VEHICLES:
        if v.get("dual"):
            for mode, tag in (("real", "real"), ("bal", "bal")):
                e, d = v["dual"][mode]
                out += ("\nswitch (FEAT_TRAINS, SELF, sw_{0}_power_{1}, current_railtype) {{\n"
                        "    ELRL: return {2};\n"
                        "          return {3};\n}}\n").format(v["nml"], tag, e, d)
            out += ("\nswitch (FEAT_TRAINS, SELF, sw_{0}_effect, current_railtype) {{\n"
                    "    ELRL: return visual_effect_and_powered(VISUAL_EFFECT_ELECTRIC, 0, DISABLE_WAGON_POWER);\n"
                    "          return visual_effect_and_powered(VISUAL_EFFECT_DIESEL, 0, DISABLE_WAGON_POWER);\n"
                    "}}\n").format(v["nml"])

    # hidden articulated parts first, so the switches can name them
    out += "\n/* ------------------------------- hidden articulated halves -- */\n\n"
    for v in VEHICLES:
        if v.get("hidden"):
            out += item_block(v) + "\n"

    for v in VEHICLES:
        if v.get("artic"):
            out += ("switch (FEAT_TRAINS, SELF, sw_{0}_artic, extra_callback_info1) {{\n"
                    "    1: return {1};\n"
                    "       return CB_RESULT_NO_MORE_ARTICULATED_PARTS;\n}}\n\n"
                    ).format(v["nml"], v["artic"])

    out += "/* ---------------------------------------- buyable vehicles -- */\n\n"
    for v in VEHICLES:
        if not v.get("hidden"):
            out += item_block(v) + "\n"

    out += ("/* ------------------------------------------------------------------\n"
            " * Game-balanced stat set. OpenTTD skips this whole block unless the\n"
            " * NewGRF parameter is set to 1, so the realistic values above stand.\n"
            " * ------------------------------------------------------------------ */\n"
            "if (stats == 1) {\n")
    for v in VEHICLES:
        out += override_block(v)
    out += "}\n"

    with open(os.path.join(HERE, "njtransit.pnml"), "w") as f:
        f.write(out)

    # ------------------------------------------------------------- strings --
    lng = ["##grflangid 0x01", ""]
    lng.append("STR_GRF_NAME                :NJ TRANSIT + PATH Trainset")
    lng.append(
        "STR_GRF_DESC                :{ORANGE}NJ TRANSIT + PATH Trainset{}{BLACK}"
        "Modern New Jersey rail: ALP-46, ALP-46A and ALP-45DP electrics, the PL42AC "
        "diesel, Arrow III EMUs, Comet V coaches, MultiLevel cars, and three "
        "generations of PATH rapid transit.{}{}Set {GOLD}Statistics{BLACK} below to "
        "choose realistic prototype figures or game-balanced ones.")
    lng.append("")
    lng.append("STR_PARAM_STATS             :Statistics")
    lng.append("STR_PARAM_STATS_DESC        :Realistic uses published prototype figures. "
               "Game-balanced scales capacity, power, speed and cost so the set sits "
               "alongside OpenTTD's own vehicles. Change this before starting a game.")
    lng.append("STR_PARAM_REALISTIC         :Realistic")
    lng.append("STR_PARAM_BALANCED          :Game-balanced")
    lng.append("")
    lng.append("# vehicle names")
    for v in VEHICLES:
        lng.append("STR_NAME_{:<19}:{}".format(v["nml"].upper(), v["name"]))
    lng.append("")
    lng.append("# purchase window information")
    for v in VEHICLES:
        if v.get("purchase"):
            lng.append("STR_PURCHASE_{:<15}:{}".format(v["nml"].upper(), v["purchase"]))
    lng.append("")

    with open(os.path.join(HERE, "lang", "english.lng"), "w") as f:
        f.write("\n".join(lng))

    print("wrote njtransit.pnml ({} items) and lang/english.lng".format(len(VEHICLES)))


if __name__ == "__main__":
    main()
